"""Pre-Commit Review hook installer (Phase E, section 6, Core tier).

Installs a small ``.git/hooks/pre-commit`` script into the developer's own
project that shells out to ``python -m spiced.core.precommit_check
<project_path>`` (see that module's docstring for why a direct module
invocation was chosen over a packaged console-script entry point). Opt-in
per project (``Project.precommit_review_enabled``, same toggle shape as the
Unity test runner / Build Pipeline) — this module has no gate of its own,
matching ``connectors.unity_build``'s "pure mechanism" convention; the
caller (the Projects screen) is responsible for checking the opt-in first.

Never silently overwrites a hook that wasn't written by Spiced: every hook
Spiced installs starts with a distinct marker comment
(``# spiced-precommit-hook``), and ``install_hook`` refuses to touch an
existing ``pre-commit`` file that lacks it — the developer decides whether
to back it up or remove it manually instead.
"""

from __future__ import annotations

import stat
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

HOOK_MARKER = "# spiced-precommit-hook"
GIT_TIMEOUT_S = 10

_HOOK_TEMPLATE = """#!/bin/sh
{marker}
# Generated by Spiced (Pre-Commit Review). Safe to edit or delete — Spiced
# will not overwrite this file again unless this marker comment stays.
# Always exits 0: this is a heads-up, never a commit gate.

"{python}" -m spiced.core.precommit_check "{project_path}"
exit 0
"""


class NotAGitRepoError(RuntimeError):
    """Raised when git doesn't recognize the target folder (or one of its
    parent folders) as a working tree -- or git itself isn't runnable."""


class ForeignHookExistsError(RuntimeError):
    """Raised when an existing pre-commit hook wasn't written by Spiced."""


@dataclass(frozen=True)
class HookInstallResult:
    hook_path: str
    installed: bool


def _run_git(args: list[str], cwd: str | Path) -> subprocess.CompletedProcess[str] | None:
    """Run a git subcommand with ``cwd`` as the working directory.

    Returns ``None`` (never raises) if git itself can't be run at all --
    not installed, or timed out -- so callers can treat that the same as
    "not a git repo" instead of crashing.
    """
    try:
        return subprocess.run(
            ["git", *args],
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=GIT_TIMEOUT_S,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None


def is_git_repo(project_path: str | Path) -> bool:
    """True iff git recognizes ``project_path`` as being inside a working
    tree. Delegates to git itself (``git rev-parse --is-inside-work-tree``)
    rather than guessing from the filesystem, so this correctly handles
    worktrees/submodules (where ``.git`` is a file, not a directory) and a
    Unity folder that's nested inside a parent repo rather than being the
    repo root itself -- a plain ``(project_path / ".git").is_dir()`` check
    gets both of those wrong.
    """
    result = _run_git(["rev-parse", "--is-inside-work-tree"], project_path)
    return result is not None and result.returncode == 0 and result.stdout.strip() == "true"


def hooks_dir(project_path: str | Path) -> Path:
    """Resolve the real git hooks directory for ``project_path`` via
    ``git rev-parse --git-path hooks``.

    This (rather than a manual ``<project_path>/.git/hooks`` join) is what
    git itself uses, so it stays correct for worktrees, submodules, and
    relocated ``.git`` dirs, and also for a Unity folder that's a
    subdirectory of the actual repo root. ``--git-path`` can print either a
    path relative to ``project_path`` or an absolute one depending on the
    repo layout -- joining it onto ``project_path`` and resolving handles
    both, since joining an absolute path onto a base path discards the base.

    Raises ``NotAGitRepoError`` if git can't resolve one.
    """
    result = _run_git(["rev-parse", "--git-path", "hooks"], project_path)
    if result is None or result.returncode != 0:
        raise NotAGitRepoError(
            f"{project_path} doesn't look like a git repository -- make sure git is installed "
            "and this folder (or one of its parent folders) has been initialized with "
            "`git init`."
        )
    output = result.stdout.strip()
    return (Path(project_path) / output).resolve()


def is_spiced_hook(hook_path: Path) -> bool:
    """True if ``hook_path`` doesn't exist yet, or exists and carries Spiced's
    marker comment — i.e. it's safe for ``install_hook`` to (re)write."""
    if not hook_path.is_file():
        return True
    try:
        text = hook_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return HOOK_MARKER in text


def install_hook(
    project_path: str | Path, python_executable: str | None = None
) -> HookInstallResult:
    """Write ``.git/hooks/pre-commit``, refusing to clobber a foreign hook.

    Raises ``NotAGitRepoError`` if git doesn't recognize ``project_path`` as
    a working tree, and ``ForeignHookExistsError`` if a pre-commit hook
    already exists and wasn't written by Spiced.
    """
    root = Path(project_path)
    if not is_git_repo(root):
        raise NotAGitRepoError(
            f"{root} doesn't look like a git repository -- make sure git is installed and "
            "this folder (or one of its parent folders) has been initialized with `git init`."
        )

    hooks = hooks_dir(root)
    hooks.mkdir(parents=True, exist_ok=True)
    hook_path = hooks / "pre-commit"

    if not is_spiced_hook(hook_path):
        raise ForeignHookExistsError(
            f"{hook_path} already exists and wasn't written by Spiced. Back it up or remove it "
            "yourself, then try again — Spiced never overwrites a hook it didn't create."
        )

    python = python_executable or sys.executable
    content = _HOOK_TEMPLATE.format(marker=HOOK_MARKER, python=python, project_path=str(root))
    hook_path.write_text(content, encoding="utf-8", newline="\n")
    _make_executable(hook_path)
    return HookInstallResult(hook_path=str(hook_path), installed=True)


def uninstall_hook(project_path: str | Path) -> bool:
    """Remove a Spiced-installed hook. Returns False (no-op) for a foreign or
    missing hook, or if the project isn't (or is no longer) a git repository
    — never deletes a hook Spiced didn't write, and never raises just
    because there's nothing there to remove."""
    try:
        hooks = hooks_dir(project_path)
    except NotAGitRepoError:
        return False
    hook_path = hooks / "pre-commit"
    if not hook_path.is_file() or not is_spiced_hook(hook_path):
        return False
    hook_path.unlink()
    return True


def _make_executable(path: Path) -> None:
    """Best-effort ``chmod +x`` — a no-op on Windows, where Git for Windows
    runs hooks through its own shell regardless of the file mode bit."""
    try:
        mode = path.stat().st_mode
        path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError:
        pass
