"""Pre-Commit Review hook installer (Phase E, section 6, Core tier).

Installs a small ``.git/hooks/pre-commit`` script into the developer's own
project that shells out to ``python -m spiced.core.precommit_check
<project_path>`` (see that module's docstring for why a direct module
invocation was chosen over a packaged console-script entry point). Opt-in
per project (``Project.precommit_review_enabled``, same toggle shape as the
Unity test runner / Build Pipeline) — this module has no gate of its own,
matching ``connectors.unity_build``'s "pure mechanism" convention; the
caller (the Projects screen) is responsible for checking the opt-in first.

Never silently overwrites a hook that wasn't written by Spiced: every hook
Spiced installs starts with a distinct marker comment
(``# spiced-precommit-hook``), and ``install_hook`` refuses to touch an
existing ``pre-commit`` file that lacks it — the developer decides whether
to back it up or remove it manually instead.
"""

from __future__ import annotations

import stat
import sys
from dataclasses import dataclass
from pathlib import Path

HOOK_MARKER = "# spiced-precommit-hook"

_HOOK_TEMPLATE = """#!/bin/sh
{marker}
# Generated by Spiced (Pre-Commit Review). Safe to edit or delete — Spiced
# will not overwrite this file again unless this marker comment stays.
# Always exits 0: this is a heads-up, never a commit gate.

"{python}" -m spiced.core.precommit_check "{project_path}"
exit 0
"""


class NotAGitRepoError(RuntimeError):
    """Raised when the target folder has no ``.git`` directory."""


class ForeignHookExistsError(RuntimeError):
    """Raised when an existing pre-commit hook wasn't written by Spiced."""


@dataclass(frozen=True)
class HookInstallResult:
    hook_path: str
    installed: bool


def hooks_dir(project_path: str | Path) -> Path:
    return Path(project_path) / ".git" / "hooks"


def is_git_repo(project_path: str | Path) -> bool:
    return (Path(project_path) / ".git").is_dir()


def is_spiced_hook(hook_path: Path) -> bool:
    """True if ``hook_path`` doesn't exist yet, or exists and carries Spiced's
    marker comment — i.e. it's safe for ``install_hook`` to (re)write."""
    if not hook_path.is_file():
        return True
    try:
        text = hook_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return HOOK_MARKER in text


def install_hook(
    project_path: str | Path, python_executable: str | None = None
) -> HookInstallResult:
    """Write ``.git/hooks/pre-commit``, refusing to clobber a foreign hook.

    Raises ``NotAGitRepoError`` if there's no ``.git`` folder, and
    ``ForeignHookExistsError`` if a pre-commit hook already exists and
    wasn't written by Spiced.
    """
    root = Path(project_path)
    if not is_git_repo(root):
        raise NotAGitRepoError(f"{root} doesn't look like a git repository (no .git folder).")

    hooks = hooks_dir(root)
    hooks.mkdir(parents=True, exist_ok=True)
    hook_path = hooks / "pre-commit"

    if not is_spiced_hook(hook_path):
        raise ForeignHookExistsError(
            f"{hook_path} already exists and wasn't written by Spiced. Back it up or remove it "
            "yourself, then try again — Spiced never overwrites a hook it didn't create."
        )

    python = python_executable or sys.executable
    content = _HOOK_TEMPLATE.format(marker=HOOK_MARKER, python=python, project_path=str(root))
    hook_path.write_text(content, encoding="utf-8", newline="\n")
    _make_executable(hook_path)
    return HookInstallResult(hook_path=str(hook_path), installed=True)


def uninstall_hook(project_path: str | Path) -> bool:
    """Remove a Spiced-installed hook. Returns False (no-op) for a foreign or
    missing hook — never deletes a hook Spiced didn't write."""
    hook_path = hooks_dir(project_path) / "pre-commit"
    if not hook_path.is_file() or not is_spiced_hook(hook_path):
        return False
    hook_path.unlink()
    return True


def _make_executable(path: Path) -> None:
    """Best-effort ``chmod +x`` — a no-op on Windows, where Git for Windows
    runs hooks through its own shell regardless of the file mode bit."""
    try:
        mode = path.stat().st_mode
        path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError:
        pass
