"""Automated Build Pipeline mechanism: build-script write + headless trigger.

The second place Spiced launches an external Unity Editor process (the first
is ``core.unity_test_runner``) and the *only* place Spiced writes a file into
a developer's own Unity project. Both are gated the same way: opt-in, per
project, off by default — the caller (``core.build_pipeline``) is responsible
for checking the project's ``build_pipeline_enabled`` flag before calling
anything here. This module has no gate of its own; it is pure mechanism,
exactly like ``unity_test_runner``'s ``run_tests``.

Unity's own docs say there is no reliable, version-stable exit code for batch
mode, so — same philosophy as the test runner — a small JSON result file
written by the build script itself is always read regardless of the
subprocess's exit code. Unity has no built-in "-buildResults"-style flag for
custom build methods, so the result file's path is passed as a plain custom
command-line argument (``-spicedResultFile``) that the generated build script
reads back via ``System.Environment.GetCommandLineArgs()`` — the same
convention Phase E's Save/Load Integrity Testing spec documents for its own
result-file handshake.
"""

from __future__ import annotations

import json
import re
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

DEFAULT_TIMEOUT_S = 1800
LOG_TAIL_CHARS = 4000

DEFAULT_BUILD_TARGET = "StandaloneWindows64"
BUILD_TARGETS = ("StandaloneWindows64", "StandaloneOSX", "StandaloneLinux64")

_BUILD_SCRIPT_NAME = "SpicedBuildScript.cs"
_METHOD_RE = re.compile(r"public\s+static\s+void\s+(\w+)\s*\(")
_CLASS_RE = re.compile(r"\bclass\s+(\w+)")

# A minimal, standard Unity Editor build script: build every enabled scene in
# Build Settings to a `Builds/<Target>/` folder under the project. Clearly
# labeled as Spiced-generated in its own header comment. Reads its target
# platform and output paths from custom command-line args rather than
# hardcoding them, so one script serves any platform Spiced is asked to build.
_BUILD_SCRIPT_TEMPLATE = """\
// Generated by Spiced (https://github.com) — Automated Build Pipeline.
// Spiced only writes this file once, when no existing Assets/Editor/*.cs
// script already exposes a public static void method calling
// BuildPipeline.BuildPlayer. Edit or delete freely; Spiced will not
// overwrite a script you (or a plugin) already provide.
using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

public static class SpicedBuildScript
{
    public static void PerformBuild()
    {
        string[] args = Environment.GetCommandLineArgs();
        string resultPath = GetArg(args, "-spicedResultFile");
        string outputDir = GetArg(args, "-spicedBuildOutput");
        string targetArg = GetArg(args, "-buildTarget");

        if (string.IsNullOrEmpty(outputDir))
        {
            outputDir = Path.Combine(Application.dataPath, "..", "Builds");
        }

        BuildTarget target = ParseTarget(targetArg);
        string extension = TargetExtension(target);
        string outputPath = Path.Combine(outputDir, "SpicedBuild" + extension);

        try
        {
            Directory.CreateDirectory(outputDir);
            string[] scenes = EditorBuildSettings.scenes
                .Where(s => s.enabled)
                .Select(s => s.path)
                .ToArray();

            if (scenes.Length == 0)
            {
                WriteResult(resultPath, false, "No scenes are enabled in Build Settings.", null);
                return;
            }

            BuildPlayerOptions options = new BuildPlayerOptions
            {
                scenes = scenes,
                locationPathName = outputPath,
                target = target,
                options = BuildOptions.None,
            };

            var report = BuildPipeline.BuildPlayer(options);
            bool success = report.summary.result ==
                UnityEditor.Build.Reporting.BuildResult.Succeeded;
            WriteResult(resultPath, success, success ? null : report.summary.result.ToString(),
                success ? outputPath : null);
        }
        catch (Exception ex)
        {
            WriteResult(resultPath, false, ex.Message, null);
        }
    }

    private static string GetArg(string[] args, string name)
    {
        for (int i = 0; i < args.Length - 1; i++)
        {
            if (args[i] == name) return args[i + 1];
        }
        return null;
    }

    private static BuildTarget ParseTarget(string name)
    {
        if (string.IsNullOrEmpty(name)) return BuildTarget.StandaloneWindows64;
        switch (name)
        {
            case "StandaloneOSX": return BuildTarget.StandaloneOSX;
            case "StandaloneLinux64": return BuildTarget.StandaloneLinux64;
            default: return BuildTarget.StandaloneWindows64;
        }
    }

    private static string TargetExtension(BuildTarget target)
    {
        switch (target)
        {
            case BuildTarget.StandaloneOSX: return ".app";
            case BuildTarget.StandaloneLinux64: return "";
            default: return ".exe";
        }
    }

    private static void WriteResult(string path, bool success, string error, string outputPath)
    {
        if (string.IsNullOrEmpty(path)) return;
        string errJson = error == null ? "null" : "\\"" + error.Replace("\\"", "'") + "\\"";
        string outJson = outputPath == null
            ? "null"
            : "\\"" + outputPath.Replace("\\\\", "/") + "\\"";
        string json = "{\\"success\\":" + (success ? "true" : "false")
            + ",\\"error\\":" + errJson
            + ",\\"output_path\\":" + outJson
            + "}";
        File.WriteAllText(path, json);
    }
}
"""


@dataclass(frozen=True)
class BuildScriptInfo:
    class_name: str
    method_name: str
    path: str
    generated: bool  # True when Spiced just wrote this file

    @property
    def execute_method(self) -> str:
        return f"{self.class_name}.{self.method_name}"


def find_existing_build_script(project_path: str | Path) -> BuildScriptInfo | None:
    """Look for an existing ``Assets/Editor/*.cs`` build entry point.

    Recognized by the combination of a ``public static void`` method and a
    call to ``BuildPipeline.BuildPlayer`` somewhere in the same file — a
    heuristic, not a compiler, but matches the vast majority of hand-written
    Unity build scripts.

    Known limitation, worth being upfront about: ``run_build`` below only
    learns whether a build succeeded by reading back a small JSON result file
    the *build script itself* writes, using the ``-spicedResultFile``/
    ``-spicedBuildOutput`` custom args Spiced passes on the command line.
    Spiced's own generated script implements that handshake; a pre-existing,
    hand-written script almost certainly does not, since it has no reason to
    know about Spiced's convention. In that case ``run_build`` will report
    "no build-result file" (treated as an unknown/failed run) even if the
    build actually succeeded, until the developer's script is updated to
    write that file too. Surfaced in the Build Pipeline UI copy rather than
    silently guessing at success from the exit code, which Unity's own docs
    say isn't reliable either.
    """
    editor_dir = Path(project_path) / "Assets" / "Editor"
    if not editor_dir.is_dir():
        return None
    for cs_file in sorted(editor_dir.glob("*.cs")):
        try:
            text = cs_file.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if "BuildPipeline.BuildPlayer" not in text:
            continue
        method_match = _METHOD_RE.search(text)
        if method_match is None:
            continue
        class_match = _CLASS_RE.search(text)
        class_name = class_match.group(1) if class_match else cs_file.stem
        return BuildScriptInfo(
            class_name=class_name,
            method_name=method_match.group(1),
            path=str(cs_file),
            generated=False,
        )
    return None


def ensure_build_script(project_path: str | Path) -> BuildScriptInfo:
    """Return the build entry point to use, writing one if none exists yet.

    Caller must have already confirmed the project's ``build_pipeline_enabled``
    opt-in — this function performs a real file write into the developer's
    project with no gate of its own (see module docstring).
    """
    existing = find_existing_build_script(project_path)
    if existing is not None:
        return existing
    editor_dir = Path(project_path) / "Assets" / "Editor"
    editor_dir.mkdir(parents=True, exist_ok=True)
    script_path = editor_dir / _BUILD_SCRIPT_NAME
    script_path.write_text(_BUILD_SCRIPT_TEMPLATE, encoding="utf-8")
    return BuildScriptInfo(
        class_name="SpicedBuildScript",
        method_name="PerformBuild",
        path=str(script_path),
        generated=True,
    )


@dataclass(frozen=True)
class UnityBuildResult:
    succeeded: bool
    output_path: str | None
    log_tail: str | None
    exit_code: int | None
    timed_out: bool
    error: str | None = None


def run_build(
    unity_path: str,
    project_path: str,
    build_target: str,
    output_dir: str,
    execute_method: str,
    timeout_s: int = DEFAULT_TIMEOUT_S,
) -> UnityBuildResult:
    """Launch one headless Unity build and return its result.

    Mirrors ``unity_test_runner.run_tests``: the build's own result file is
    always read regardless of the subprocess exit code, since Unity's batch
    mode exit code is not a reliable success signal.
    """
    with tempfile.TemporaryDirectory(prefix="spiced-unity-build-") as tmp:
        log_path = Path(tmp) / "editor.log"
        result_path = Path(tmp) / "build_result.json"
        command = [
            unity_path,
            "-batchmode",
            "-projectPath",
            str(project_path),
            "-executeMethod",
            execute_method,
            "-buildTarget",
            build_target,
            "-logFile",
            str(log_path),
            "-nographics",
            "-spicedBuildOutput",
            str(output_dir),
            "-spicedResultFile",
            str(result_path),
        ]

        exit_code: int | None = None
        timed_out = False
        try:
            completed = subprocess.run(command, timeout=timeout_s, capture_output=True)
            exit_code = completed.returncode
        except subprocess.TimeoutExpired:
            timed_out = True
        except OSError as exc:
            return UnityBuildResult(
                succeeded=False,
                output_path=None,
                log_tail=None,
                exit_code=None,
                timed_out=False,
                error=f"Could not launch Unity: {exc}",
            )

        log_tail = _read_tail(log_path)
        if timed_out:
            duration = f"{timeout_s // 60} minutes" if timeout_s >= 60 else f"{timeout_s} seconds"
            return UnityBuildResult(
                succeeded=False,
                output_path=None,
                log_tail=log_tail,
                exit_code=None,
                timed_out=True,
                error=(
                    f"Unity did not finish the build within {duration} and was stopped. This "
                    "can happen on a slow first-time asset import, or a large project's first "
                    "player build."
                ),
            )

        result_data = _read_json(result_path)
        if result_data is None:
            return UnityBuildResult(
                succeeded=False,
                output_path=None,
                log_tail=log_tail,
                exit_code=exit_code,
                timed_out=False,
                error=(
                    "Unity exited without writing a build-result file. This usually means it "
                    "hit an error before or during the build — see the log excerpt below."
                ),
            )
        return UnityBuildResult(
            succeeded=bool(result_data.get("success")),
            output_path=result_data.get("output_path"),
            log_tail=log_tail,
            exit_code=exit_code,
            timed_out=False,
            error=result_data.get("error"),
        )


def _read_json(path: Path) -> dict | None:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return None
    return data if isinstance(data, dict) else None


def _read_tail(path: Path, limit: int = LOG_TAIL_CHARS) -> str | None:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    return text[-limit:] if len(text) > limit else text
