"""Visual Regression Testing mechanism: engine-side camera-capture hook +
headless trigger (Implementation Bible, Feature 2).

The third place Spiced launches an external Unity Editor process (after
``unity_test_runner`` and ``unity_build``), and the second place it writes a
file into a developer's own Unity project. Unlike ``unity_build``'s script,
this one is always (re)written by ``ensure_capture_script`` rather than
first checking for a hand-written equivalent -- there's no generic existing
convention for "move a camera to a named marker and screenshot it" a
developer would plausibly have already hand-rolled, unlike a build script.

**The marker-GameObject convention**: rather than asking a developer to type
raw camera position/rotation floats into Spiced, each key scene names one
GameObject already placed in that scene (e.g. an empty named
``SpicedCapture_MainHall``) -- the capture camera is snapped to that
GameObject's transform. See ``docs/visual_regression_capture_hook.md``.

Same "always read the result file regardless of subprocess exit code"
philosophy as ``unity_build``/``unity_test_runner``, since Unity's own docs
say batch-mode exit codes aren't a reliable success signal. Unlike those two,
this command deliberately omits ``-nographics`` -- rendering a camera to a
texture needs a real graphics device, which ``-nographics`` disables.
"""

from __future__ import annotations

import json
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

DEFAULT_TIMEOUT_S = 600
LOG_TAIL_CHARS = 4000

_CAPTURE_SCRIPT_NAME = "SpicedVisualCaptureScript.cs"

# Fixed capture resolution for v1 -- not configurable, to keep the "before"
# and "after" images from two different runs directly comparable (a
# resolution change alone would otherwise register as 100% of pixels
# changed). See module docstring for the marker-GameObject convention.
_CAPTURE_WIDTH = 1920
_CAPTURE_HEIGHT = 1080

# Generated by Spiced (https://github.com) -- Visual Regression Testing.
# Always overwritten on each run (see ensure_capture_script): unlike the
# Automated Build Pipeline's build script, there's no hand-written
# equivalent of this to preserve.
_CAPTURE_SCRIPT_TEMPLATE = f"""\
// Generated by Spiced (https://github.com) — Visual Regression Testing.
// Spiced (re)writes this file on every capture run; don't hand-edit it.
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

public static class SpicedVisualCaptureScript
{{
    private const int Width = {_CAPTURE_WIDTH};
    private const int Height = {_CAPTURE_HEIGHT};

    [Serializable]
    private class CaptureRequest
    {{
        public string scene_path;
        public string marker_name;
        public string output_path;
    }}

    [Serializable]
    private class CaptureRequestList
    {{
        public CaptureRequest[] requests;
    }}

    public static void PerformCapture()
    {{
        string[] args = Environment.GetCommandLineArgs();
        string configPath = GetArg(args, "-spicedCaptureConfig");
        string resultPath = GetArg(args, "-spicedResultFile");
        var outcomes = new List<string>();

        try
        {{
            if (string.IsNullOrEmpty(configPath) || !File.Exists(configPath))
            {{
                WriteResult(resultPath, outcomes, "No capture config file found.");
                return;
            }}

            CaptureRequestList config = JsonUtility.FromJson<CaptureRequestList>(
                File.ReadAllText(configPath));
            if (config == null || config.requests == null)
            {{
                WriteResult(resultPath, outcomes, "Capture config had no requests.");
                return;
            }}

            foreach (var req in config.requests)
            {{
                try
                {{
                    CaptureOne(req);
                    outcomes.Add(OutcomeJson(req.scene_path, req.output_path, true, null));
                }}
                catch (Exception ex)
                {{
                    outcomes.Add(OutcomeJson(req.scene_path, req.output_path, false, ex.Message));
                }}
            }}

            WriteResult(resultPath, outcomes, null);
        }}
        catch (Exception ex)
        {{
            WriteResult(resultPath, outcomes, ex.Message);
        }}
        finally
        {{
            EditorApplication.Exit(0);
        }}
    }}

    private static void CaptureOne(CaptureRequest req)
    {{
        EditorSceneManager.OpenScene(req.scene_path);
        GameObject marker = GameObject.Find(req.marker_name);
        if (marker == null)
        {{
            throw new Exception("No GameObject named '" + req.marker_name + "' found in "
                + req.scene_path);
        }}

        GameObject camGo = new GameObject("SpicedCaptureCamera");
        Camera cam = camGo.AddComponent<Camera>();
        camGo.transform.position = marker.transform.position;
        camGo.transform.rotation = marker.transform.rotation;

        RenderTexture rt = new RenderTexture(Width, Height, 24);
        Texture2D screenshot = new Texture2D(Width, Height, TextureFormat.RGB24, false);
        try
        {{
            cam.targetTexture = rt;
            cam.Render();
            RenderTexture.active = rt;
            screenshot.ReadPixels(new Rect(0, 0, Width, Height), 0, 0);
            screenshot.Apply();

            string outDir = Path.GetDirectoryName(req.output_path);
            if (!string.IsNullOrEmpty(outDir)) Directory.CreateDirectory(outDir);
            File.WriteAllBytes(req.output_path, screenshot.EncodeToPNG());
        }}
        finally
        {{
            RenderTexture.active = null;
            cam.targetTexture = null;
            rt.Release();
            UnityEngine.Object.DestroyImmediate(camGo);
            UnityEngine.Object.DestroyImmediate(screenshot);
            UnityEngine.Object.DestroyImmediate(rt);
        }}
    }}

    private static string GetArg(string[] args, string name)
    {{
        for (int i = 0; i < args.Length - 1; i++)
        {{
            if (args[i] == name) return args[i + 1];
        }}
        return null;
    }}

    private static string OutcomeJson(
        string scenePath, string outputPath, bool success, string error)
    {{
        string errJson = error == null ? "null" : "\\"" + Esc(error) + "\\"";
        return "{{\\"scene_path\\":\\"" + Esc(scenePath) + "\\",\\"success\\":"
            + (success ? "true" : "false") + ",\\"error\\":" + errJson
            + ",\\"output_path\\":\\"" + Esc(outputPath) + "\\"}}";
    }}

    private static string Esc(string s)
    {{
        return (s ?? "").Replace("\\\\", "\\\\\\\\").Replace("\\"", "\\\\\\"");
    }}

    private static void WriteResult(string path, List<string> outcomes, string runError)
    {{
        if (string.IsNullOrEmpty(path)) return;
        string errJson = runError == null ? "null" : "\\"" + Esc(runError) + "\\"";
        string json = "{{\\"run_error\\":" + errJson + ",\\"captures\\":["
            + string.Join(",", outcomes) + "]}}";
        File.WriteAllText(path, json);
    }}
}}
"""


@dataclass(frozen=True)
class SceneCaptureRequest:
    scene_path: str
    marker_name: str
    output_path: str


@dataclass(frozen=True)
class SceneCaptureOutcome:
    scene_path: str
    output_path: str
    succeeded: bool
    error: str | None = None


@dataclass(frozen=True)
class CaptureRunResult:
    outcomes: list[SceneCaptureOutcome] = field(default_factory=list)
    log_tail: str | None = None
    exit_code: int | None = None
    timed_out: bool = False
    error: str | None = None  # whole-run error; individual scenes can still fail without this


def ensure_capture_script(project_path: str | Path) -> str:
    """(Re)write the capture script into ``Assets/Editor/`` and return its path.

    Always overwrites -- see module docstring for why, unlike
    ``unity_build.ensure_build_script``, this never looks for an existing
    hand-written equivalent.
    """
    editor_dir = Path(project_path) / "Assets" / "Editor"
    editor_dir.mkdir(parents=True, exist_ok=True)
    script_path = editor_dir / _CAPTURE_SCRIPT_NAME
    script_path.write_text(_CAPTURE_SCRIPT_TEMPLATE, encoding="utf-8")
    return str(script_path)


def run_capture(
    unity_path: str,
    project_path: str,
    requests: list[SceneCaptureRequest],
    timeout_s: int = DEFAULT_TIMEOUT_S,
) -> CaptureRunResult:
    """Launch one headless Unity capture run for every scene in ``requests``."""
    ensure_capture_script(project_path)

    with tempfile.TemporaryDirectory(prefix="spiced-visual-capture-") as tmp:
        config_path = Path(tmp) / "capture_config.json"
        result_path = Path(tmp) / "capture_result.json"
        log_path = Path(tmp) / "editor.log"
        config_path.write_text(
            json.dumps(
                {
                    "requests": [
                        {
                            "scene_path": r.scene_path,
                            "marker_name": r.marker_name,
                            "output_path": r.output_path,
                        }
                        for r in requests
                    ]
                }
            ),
            encoding="utf-8",
        )

        command = [
            unity_path,
            "-batchmode",
            "-projectPath",
            str(project_path),
            "-executeMethod",
            "SpicedVisualCaptureScript.PerformCapture",
            "-spicedCaptureConfig",
            str(config_path),
            "-spicedResultFile",
            str(result_path),
            "-logFile",
            str(log_path),
        ]

        exit_code: int | None = None
        timed_out = False
        try:
            completed = subprocess.run(command, timeout=timeout_s, capture_output=True)
            exit_code = completed.returncode
        except subprocess.TimeoutExpired:
            timed_out = True
        except OSError as exc:
            return CaptureRunResult(error=f"Could not launch Unity: {exc}")

        log_tail = _read_tail(log_path)
        if timed_out:
            duration = f"{timeout_s // 60} minutes" if timeout_s >= 60 else f"{timeout_s} seconds"
            return CaptureRunResult(
                log_tail=log_tail,
                timed_out=True,
                error=(
                    f"Unity did not finish capturing within {duration} and was stopped. This "
                    "can happen on a slow first-time asset import, or if Unity is stuck on a "
                    "dialog batch mode can't dismiss."
                ),
            )

        result_data = _read_json(result_path)
        if result_data is None:
            return CaptureRunResult(
                log_tail=log_tail,
                exit_code=exit_code,
                error=(
                    "Unity exited without writing a capture-result file. This usually means it "
                    "hit an error before capture could run -- see the log excerpt below."
                ),
            )

        outcomes = [
            SceneCaptureOutcome(
                scene_path=c.get("scene_path", ""),
                output_path=c.get("output_path", ""),
                succeeded=bool(c.get("success")),
                error=c.get("error"),
            )
            for c in result_data.get("captures", [])
        ]
        return CaptureRunResult(
            outcomes=outcomes,
            log_tail=log_tail,
            exit_code=exit_code,
            error=result_data.get("run_error"),
        )


def _read_json(path: Path) -> dict | None:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return None
    return data if isinstance(data, dict) else None


def _read_tail(path: Path, limit: int = LOG_TAIL_CHARS) -> str | None:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    return text[-limit:] if len(text) > limit else text
