"""Shader Variant & Compile Bloat Analysis mechanism: engine-side variant-
count export hook (Implementation Bible, Feature 6).

The fifth place Spiced launches an external Unity Editor process. Rather
than regex-parsing Unity's shader-variant-stripping *log text* (the Bible's
suggested approach) -- a format this project has no verified real sample
of, and the same category of risk ``core.shader_performance_profiling``
and ``connectors.unity_controller_scan`` already document declining to
guess at -- this reads variant counts through Unity's documented public
Editor API, ``UnityEditor.ShaderUtil.GetVariantCount``, the same API
Unity's own "reducing shader variants" guidance points developers at. This
hasn't been verified against a real Unity Editor in this environment (none
is installed here); it's the best-documented, lowest-risk option available
without one, the same reasoning Feature 3's mesh-pivot export applied.

No rendering needed, so this uses ``-nographics`` like
``unity_asset_export``.
"""

from __future__ import annotations

import json
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

DEFAULT_TIMEOUT_S = 600
LOG_TAIL_CHARS = 4000

_EXPORT_SCRIPT_NAME = "SpicedShaderVariantExportScript.cs"

# Generated by Spiced (https://github.com) -- Shader Variant & Compile Bloat
# Analysis. Always overwritten on each run, same reasoning as
# unity_visual_capture / unity_asset_export's generated scripts.
_EXPORT_SCRIPT_TEMPLATE = """\
// Generated by Spiced (https://github.com) -- Shader Variant & Compile Bloat Analysis.
// Spiced (re)writes this file on every scan run; don't hand-edit it.
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

public static class SpicedShaderVariantExportScript
{
    [Serializable]
    private class ExportRequest
    {
        public string[] shader_paths;
    }

    public static void PerformExport()
    {
        string[] args = Environment.GetCommandLineArgs();
        string configPath = GetArg(args, "-spicedShaderPaths");
        string resultPath = GetArg(args, "-spicedResultFile");
        var outcomes = new List<string>();

        try
        {
            if (string.IsNullOrEmpty(configPath) || !File.Exists(configPath))
            {
                WriteResult(resultPath, outcomes, "No shader path config file found.");
                return;
            }

            ExportRequest config = JsonUtility.FromJson<ExportRequest>(
                File.ReadAllText(configPath));
            if (config == null || config.shader_paths == null)
            {
                WriteResult(resultPath, outcomes, "Shader path config had no shader_paths.");
                return;
            }

            foreach (var shaderPath in config.shader_paths)
            {
                try
                {
                    Shader shader = AssetDatabase.LoadAssetAtPath<Shader>(shaderPath);
                    if (shader == null)
                    {
                        throw new Exception("Could not load this asset as a Shader.");
                    }
                    int variantCount = ShaderUtil.GetVariantCount(shader, true);
                    int passCount = ShaderUtil.GetShaderPassCount(shader);
                    outcomes.Add(SuccessJson(shaderPath, variantCount, passCount));
                }
                catch (Exception ex)
                {
                    outcomes.Add(ErrorJson(shaderPath, ex.Message));
                }
            }

            WriteResult(resultPath, outcomes, null);
        }
        catch (Exception ex)
        {
            WriteResult(resultPath, outcomes, ex.Message);
        }
        finally
        {
            EditorApplication.Exit(0);
        }
    }

    private static string GetArg(string[] args, string name)
    {
        for (int i = 0; i < args.Length - 1; i++)
        {
            if (args[i] == name) return args[i + 1];
        }
        return null;
    }

    private static string SuccessJson(string shaderPath, int variantCount, int passCount)
    {
        return "{\\"shader_path\\":\\"" + Esc(shaderPath)
            + "\\",\\"success\\":true,\\"error\\":null"
            + ",\\"variant_count\\":" + variantCount + ",\\"pass_count\\":" + passCount + "}";
    }

    private static string ErrorJson(string shaderPath, string error)
    {
        return "{\\"shader_path\\":\\"" + Esc(shaderPath)
            + "\\",\\"success\\":false,\\"error\\":\\""
            + Esc(error) + "\\",\\"variant_count\\":null,\\"pass_count\\":null}";
    }

    private static string Esc(string s)
    {
        return (s ?? "").Replace("\\\\", "\\\\\\\\").Replace("\\"", "\\\\\\"");
    }

    private static void WriteResult(string path, List<string> outcomes, string runError)
    {
        if (string.IsNullOrEmpty(path)) return;
        string errJson = runError == null ? "null" : "\\"" + Esc(runError) + "\\"";
        string json = "{\\"run_error\\":" + errJson + ",\\"shaders\\":["
            + string.Join(",", outcomes) + "]}";
        File.WriteAllText(path, json);
    }
}
"""


@dataclass(frozen=True)
class ShaderVariantOutcome:
    shader_path: str
    succeeded: bool
    error: str | None = None
    variant_count: int | None = None
    pass_count: int | None = None


@dataclass(frozen=True)
class ShaderVariantRunResult:
    outcomes: list[ShaderVariantOutcome] = field(default_factory=list)
    log_tail: str | None = None
    exit_code: int | None = None
    timed_out: bool = False
    error: str | None = None


def ensure_export_script(project_path: str | Path) -> str:
    editor_dir = Path(project_path) / "Assets" / "Editor"
    editor_dir.mkdir(parents=True, exist_ok=True)
    script_path = editor_dir / _EXPORT_SCRIPT_NAME
    script_path.write_text(_EXPORT_SCRIPT_TEMPLATE, encoding="utf-8")
    return str(script_path)


def run_export(
    unity_path: str,
    project_path: str,
    shader_paths: list[str],
    timeout_s: int = DEFAULT_TIMEOUT_S,
) -> ShaderVariantRunResult:
    """Launch one headless Unity export run for every shader in
    ``shader_paths`` (Unity-relative, e.g. ``Assets/Shaders/Toon.shader``)."""
    ensure_export_script(project_path)

    with tempfile.TemporaryDirectory(prefix="spiced-shader-variant-") as tmp:
        config_path = Path(tmp) / "shader_paths.json"
        result_path = Path(tmp) / "export_result.json"
        log_path = Path(tmp) / "editor.log"
        config_path.write_text(
            json.dumps({"shader_paths": shader_paths}), encoding="utf-8"
        )

        command = [
            unity_path,
            "-batchmode",
            "-projectPath",
            str(project_path),
            "-executeMethod",
            "SpicedShaderVariantExportScript.PerformExport",
            "-spicedShaderPaths",
            str(config_path),
            "-spicedResultFile",
            str(result_path),
            "-logFile",
            str(log_path),
            "-nographics",
        ]

        exit_code: int | None = None
        timed_out = False
        try:
            completed = subprocess.run(command, timeout=timeout_s, capture_output=True)
            exit_code = completed.returncode
        except subprocess.TimeoutExpired:
            timed_out = True
        except OSError as exc:
            return ShaderVariantRunResult(error=f"Could not launch Unity: {exc}")

        log_tail = _read_tail(log_path)
        if timed_out:
            duration = f"{timeout_s // 60} minutes" if timeout_s >= 60 else f"{timeout_s} seconds"
            return ShaderVariantRunResult(
                log_tail=log_tail,
                timed_out=True,
                error=(
                    f"Unity did not finish the export within {duration} and was stopped. This "
                    "can happen on a slow first-time asset import, or if Unity is stuck on a "
                    "dialog batch mode can't dismiss."
                ),
            )

        result_data = _read_json(result_path)
        if result_data is None:
            return ShaderVariantRunResult(
                log_tail=log_tail,
                exit_code=exit_code,
                error=(
                    "Unity exited without writing an export-result file. This usually means it "
                    "hit an error before the export could run -- see the log excerpt below."
                ),
            )

        outcomes = [
            ShaderVariantOutcome(
                shader_path=s.get("shader_path", ""),
                succeeded=bool(s.get("success")),
                error=s.get("error"),
                variant_count=s.get("variant_count"),
                pass_count=s.get("pass_count"),
            )
            for s in result_data.get("shaders", [])
        ]
        return ShaderVariantRunResult(
            outcomes=outcomes,
            log_tail=log_tail,
            exit_code=exit_code,
            error=result_data.get("run_error"),
        )


def _read_json(path: Path) -> dict | None:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return None
    return data if isinstance(data, dict) else None


def _read_tail(path: Path, limit: int = LOG_TAIL_CHARS) -> str | None:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    return text[-limit:] if len(text) > limit else text
