"""Asset Technical QA Scan mechanism: engine-side mesh-pivot export hook
(Implementation Bible, Feature 3).

The fourth place Spiced launches an external Unity Editor process (after
``unity_test_runner``, ``unity_build``, ``unity_visual_capture``). A mesh
asset's *pivot* -- how far its geometry sits from its own local origin,
relative to its own size -- isn't reliably extractable from a raw .fbx/.obj
file or its ``.meta`` sidecar (unlike a texture's mipmap setting, which
*is* plain text in ``.meta`` -- see ``core.asset_review_queue``); it needs
Unity's own mesh-import processing. This script loads each asset the way
Unity already does and reads ``Mesh.bounds`` back via the well-documented
``UnityEditor``/``UnityEngine`` API, rather than guessing at FBX binary
layout.

Unlike ``unity_visual_capture``, this reads data only (no rendering), so it
uses ``-nographics`` like ``unity_build``/``unity_test_runner`` for a faster,
simpler headless run.
"""

from __future__ import annotations

import json
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

DEFAULT_TIMEOUT_S = 600
LOG_TAIL_CHARS = 4000

_EXPORT_SCRIPT_NAME = "SpicedAssetExportScript.cs"

# Generated by Spiced (https://github.com) -- Asset Technical QA Scan.
# Always overwritten on each run (see ensure_export_script), same "no
# hand-written equivalent to preserve" reasoning as unity_visual_capture's
# script.
_EXPORT_SCRIPT_TEMPLATE = """\
// Generated by Spiced (https://github.com) -- Asset Technical QA Scan.
// Spiced (re)writes this file on every scan run; don't hand-edit it.
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using UnityEditor;
using UnityEngine;

public static class SpicedAssetExportScript
{
    [Serializable]
    private class ExportRequest
    {
        public string[] asset_paths;
    }

    public static void PerformExport()
    {
        string[] args = Environment.GetCommandLineArgs();
        string configPath = GetArg(args, "-spicedAssetPaths");
        string resultPath = GetArg(args, "-spicedResultFile");
        var outcomes = new List<string>();

        try
        {
            if (string.IsNullOrEmpty(configPath) || !File.Exists(configPath))
            {
                WriteResult(resultPath, outcomes, "No asset path config file found.");
                return;
            }

            ExportRequest config = JsonUtility.FromJson<ExportRequest>(
                File.ReadAllText(configPath));
            if (config == null || config.asset_paths == null)
            {
                WriteResult(resultPath, outcomes, "Asset path config had no asset_paths.");
                return;
            }

            foreach (var assetPath in config.asset_paths)
            {
                try
                {
                    Bounds bounds = GetMeshBounds(assetPath);
                    outcomes.Add(
                        SuccessJson(assetPath, bounds.center.magnitude, bounds.size.magnitude));
                }
                catch (Exception ex)
                {
                    outcomes.Add(ErrorJson(assetPath, ex.Message));
                }
            }

            WriteResult(resultPath, outcomes, null);
        }
        catch (Exception ex)
        {
            WriteResult(resultPath, outcomes, ex.Message);
        }
        finally
        {
            EditorApplication.Exit(0);
        }
    }

    private static Bounds GetMeshBounds(string assetPath)
    {
        var go = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);
        if (go != null)
        {
            var filter = go.GetComponentInChildren<MeshFilter>();
            if (filter != null && filter.sharedMesh != null)
            {
                return filter.sharedMesh.bounds;
            }
            var skinned = go.GetComponentInChildren<SkinnedMeshRenderer>();
            if (skinned != null && skinned.sharedMesh != null)
            {
                return skinned.sharedMesh.bounds;
            }
            throw new Exception("No mesh found on this asset's GameObject hierarchy.");
        }

        var mesh = AssetDatabase.LoadAssetAtPath<Mesh>(assetPath);
        if (mesh != null)
        {
            return mesh.bounds;
        }

        throw new Exception("Could not load this asset as a GameObject or Mesh.");
    }

    private static string GetArg(string[] args, string name)
    {
        for (int i = 0; i < args.Length - 1; i++)
        {
            if (args[i] == name) return args[i + 1];
        }
        return null;
    }

    private static string F(float value)
    {
        return value.ToString(CultureInfo.InvariantCulture);
    }

    private static string SuccessJson(string assetPath, float pivotOffset, float boundsSize)
    {
        return "{\\"asset_path\\":\\"" + Esc(assetPath) + "\\",\\"success\\":true,\\"error\\":null"
            + ",\\"pivot_offset\\":" + F(pivotOffset) + ",\\"bounds_size\\":" + F(boundsSize) + "}";
    }

    private static string ErrorJson(string assetPath, string error)
    {
        return "{\\"asset_path\\":\\"" + Esc(assetPath) + "\\",\\"success\\":false,\\"error\\":\\""
            + Esc(error) + "\\",\\"pivot_offset\\":null,\\"bounds_size\\":null}";
    }

    private static string Esc(string s)
    {
        return (s ?? "").Replace("\\\\", "\\\\\\\\").Replace("\\"", "\\\\\\"");
    }

    private static void WriteResult(string path, List<string> outcomes, string runError)
    {
        if (string.IsNullOrEmpty(path)) return;
        string errJson = runError == null ? "null" : "\\"" + Esc(runError) + "\\"";
        string json = "{\\"run_error\\":" + errJson + ",\\"assets\\":["
            + string.Join(",", outcomes) + "]}";
        File.WriteAllText(path, json);
    }
}
"""


@dataclass(frozen=True)
class AssetExportOutcome:
    asset_path: str
    succeeded: bool
    error: str | None = None
    pivot_offset: float | None = None
    bounds_size: float | None = None


@dataclass(frozen=True)
class AssetExportRunResult:
    outcomes: list[AssetExportOutcome] = field(default_factory=list)
    log_tail: str | None = None
    exit_code: int | None = None
    timed_out: bool = False
    error: str | None = None


def ensure_export_script(project_path: str | Path) -> str:
    """(Re)write the export script into ``Assets/Editor/`` and return its path."""
    editor_dir = Path(project_path) / "Assets" / "Editor"
    editor_dir.mkdir(parents=True, exist_ok=True)
    script_path = editor_dir / _EXPORT_SCRIPT_NAME
    script_path.write_text(_EXPORT_SCRIPT_TEMPLATE, encoding="utf-8")
    return str(script_path)


def run_export(
    unity_path: str,
    project_path: str,
    asset_paths: list[str],
    timeout_s: int = DEFAULT_TIMEOUT_S,
) -> AssetExportRunResult:
    """Launch one headless Unity export run for every asset in ``asset_paths``
    (Unity-relative paths, e.g. ``Assets/Models/Chair.fbx``)."""
    ensure_export_script(project_path)

    with tempfile.TemporaryDirectory(prefix="spiced-asset-export-") as tmp:
        config_path = Path(tmp) / "asset_paths.json"
        result_path = Path(tmp) / "export_result.json"
        log_path = Path(tmp) / "editor.log"
        config_path.write_text(
            json.dumps({"asset_paths": asset_paths}), encoding="utf-8"
        )

        command = [
            unity_path,
            "-batchmode",
            "-projectPath",
            str(project_path),
            "-executeMethod",
            "SpicedAssetExportScript.PerformExport",
            "-spicedAssetPaths",
            str(config_path),
            "-spicedResultFile",
            str(result_path),
            "-logFile",
            str(log_path),
            "-nographics",
        ]

        exit_code: int | None = None
        timed_out = False
        try:
            completed = subprocess.run(command, timeout=timeout_s, capture_output=True)
            exit_code = completed.returncode
        except subprocess.TimeoutExpired:
            timed_out = True
        except OSError as exc:
            return AssetExportRunResult(error=f"Could not launch Unity: {exc}")

        log_tail = _read_tail(log_path)
        if timed_out:
            duration = f"{timeout_s // 60} minutes" if timeout_s >= 60 else f"{timeout_s} seconds"
            return AssetExportRunResult(
                log_tail=log_tail,
                timed_out=True,
                error=(
                    f"Unity did not finish the export within {duration} and was stopped. This "
                    "can happen on a slow first-time asset import, or if Unity is stuck on a "
                    "dialog batch mode can't dismiss."
                ),
            )

        result_data = _read_json(result_path)
        if result_data is None:
            return AssetExportRunResult(
                log_tail=log_tail,
                exit_code=exit_code,
                error=(
                    "Unity exited without writing an export-result file. This usually means it "
                    "hit an error before the export could run -- see the log excerpt below."
                ),
            )

        outcomes = [
            AssetExportOutcome(
                asset_path=a.get("asset_path", ""),
                succeeded=bool(a.get("success")),
                error=a.get("error"),
                pivot_offset=a.get("pivot_offset"),
                bounds_size=a.get("bounds_size"),
            )
            for a in result_data.get("assets", [])
        ]
        return AssetExportRunResult(
            outcomes=outcomes,
            log_tail=log_tail,
            exit_code=exit_code,
            error=result_data.get("run_error"),
        )


def _read_json(path: Path) -> dict | None:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return None
    return data if isinstance(data, dict) else None


def _read_tail(path: Path, limit: int = LOG_TAIL_CHARS) -> str | None:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    return text[-limit:] if len(text) > limit else text
