"""Retarget Validation mechanism: engine-side skeleton bone-name export hook
(Implementation Bible, Feature 7).

The sixth place Spiced launches an external Unity Editor process. A rigged
model's bone hierarchy is a plain ``Transform`` hierarchy under its root
GameObject -- this walks it with ``GetComponentsInChildren<Transform>()``,
a basic, universally-documented Unity API, rather than trying to parse an
``.fbx``'s binary/ASCII structure directly.

No rendering needed, so this uses ``-nographics`` like
``unity_asset_export``/``unity_shader_variant_export``.
"""

from __future__ import annotations

import json
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

DEFAULT_TIMEOUT_S = 600
LOG_TAIL_CHARS = 4000

_EXPORT_SCRIPT_NAME = "SpicedSkeletonExportScript.cs"

_EXPORT_SCRIPT_TEMPLATE = """\
// Generated by Spiced (https://github.com) -- Retarget Validation.
// Spiced (re)writes this file on every scan run; don't hand-edit it.
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

public static class SpicedSkeletonExportScript
{
    [Serializable]
    private class ExportRequest
    {
        public string[] model_paths;
    }

    public static void PerformExport()
    {
        string[] args = Environment.GetCommandLineArgs();
        string configPath = GetArg(args, "-spicedModelPaths");
        string resultPath = GetArg(args, "-spicedResultFile");
        var outcomes = new List<string>();

        try
        {
            if (string.IsNullOrEmpty(configPath) || !File.Exists(configPath))
            {
                WriteResult(resultPath, outcomes, "No model path config file found.");
                return;
            }

            ExportRequest config = JsonUtility.FromJson<ExportRequest>(
                File.ReadAllText(configPath));
            if (config == null || config.model_paths == null)
            {
                WriteResult(resultPath, outcomes, "Model path config had no model_paths.");
                return;
            }

            foreach (var modelPath in config.model_paths)
            {
                try
                {
                    GameObject go = AssetDatabase.LoadAssetAtPath<GameObject>(modelPath);
                    if (go == null)
                    {
                        throw new Exception("Could not load this asset as a GameObject.");
                    }
                    Transform[] all = go.GetComponentsInChildren<Transform>(true);
                    var names = new List<string>();
                    foreach (var t in all)
                    {
                        names.Add(t.name);
                    }
                    outcomes.Add(SuccessJson(modelPath, names));
                }
                catch (Exception ex)
                {
                    outcomes.Add(ErrorJson(modelPath, ex.Message));
                }
            }

            WriteResult(resultPath, outcomes, null);
        }
        catch (Exception ex)
        {
            WriteResult(resultPath, outcomes, ex.Message);
        }
        finally
        {
            EditorApplication.Exit(0);
        }
    }

    private static string GetArg(string[] args, string name)
    {
        for (int i = 0; i < args.Length - 1; i++)
        {
            if (args[i] == name) return args[i + 1];
        }
        return null;
    }

    private static string SuccessJson(string modelPath, List<string> boneNames)
    {
        var quoted = new List<string>();
        foreach (var n in boneNames)
        {
            quoted.Add("\\"" + Esc(n) + "\\"");
        }
        return "{\\"model_path\\":\\"" + Esc(modelPath) + "\\",\\"success\\":true,\\"error\\":null"
            + ",\\"bone_names\\":[" + string.Join(",", quoted) + "]}";
    }

    private static string ErrorJson(string modelPath, string error)
    {
        return "{\\"model_path\\":\\"" + Esc(modelPath)
            + "\\",\\"success\\":false,\\"error\\":\\"" + Esc(error) + "\\",\\"bone_names\\":null}";
    }

    private static string Esc(string s)
    {
        return (s ?? "").Replace("\\\\", "\\\\\\\\").Replace("\\"", "\\\\\\"");
    }

    private static void WriteResult(string path, List<string> outcomes, string runError)
    {
        if (string.IsNullOrEmpty(path)) return;
        string errJson = runError == null ? "null" : "\\"" + Esc(runError) + "\\"";
        string json = "{\\"run_error\\":" + errJson + ",\\"models\\":["
            + string.Join(",", outcomes) + "]}";
        File.WriteAllText(path, json);
    }
}
"""


@dataclass(frozen=True)
class SkeletonExportOutcome:
    model_path: str
    succeeded: bool
    error: str | None = None
    bone_names: list[str] | None = None


@dataclass(frozen=True)
class SkeletonExportRunResult:
    outcomes: list[SkeletonExportOutcome] = field(default_factory=list)
    log_tail: str | None = None
    exit_code: int | None = None
    timed_out: bool = False
    error: str | None = None


def ensure_export_script(project_path: str | Path) -> str:
    editor_dir = Path(project_path) / "Assets" / "Editor"
    editor_dir.mkdir(parents=True, exist_ok=True)
    script_path = editor_dir / _EXPORT_SCRIPT_NAME
    script_path.write_text(_EXPORT_SCRIPT_TEMPLATE, encoding="utf-8")
    return str(script_path)


def run_export(
    unity_path: str,
    project_path: str,
    model_paths: list[str],
    timeout_s: int = DEFAULT_TIMEOUT_S,
) -> SkeletonExportRunResult:
    """Launch one headless Unity export run for every model in
    ``model_paths`` (Unity-relative, e.g. ``Assets/Characters/Hero.fbx``)."""
    ensure_export_script(project_path)

    with tempfile.TemporaryDirectory(prefix="spiced-skeleton-export-") as tmp:
        config_path = Path(tmp) / "model_paths.json"
        result_path = Path(tmp) / "export_result.json"
        log_path = Path(tmp) / "editor.log"
        config_path.write_text(json.dumps({"model_paths": model_paths}), encoding="utf-8")

        command = [
            unity_path,
            "-batchmode",
            "-projectPath",
            str(project_path),
            "-executeMethod",
            "SpicedSkeletonExportScript.PerformExport",
            "-spicedModelPaths",
            str(config_path),
            "-spicedResultFile",
            str(result_path),
            "-logFile",
            str(log_path),
            "-nographics",
        ]

        exit_code: int | None = None
        timed_out = False
        try:
            completed = subprocess.run(command, timeout=timeout_s, capture_output=True)
            exit_code = completed.returncode
        except subprocess.TimeoutExpired:
            timed_out = True
        except OSError as exc:
            return SkeletonExportRunResult(error=f"Could not launch Unity: {exc}")

        log_tail = _read_tail(log_path)
        if timed_out:
            duration = f"{timeout_s // 60} minutes" if timeout_s >= 60 else f"{timeout_s} seconds"
            return SkeletonExportRunResult(
                log_tail=log_tail,
                timed_out=True,
                error=(
                    f"Unity did not finish the export within {duration} and was stopped. This "
                    "can happen on a slow first-time asset import, or if Unity is stuck on a "
                    "dialog batch mode can't dismiss."
                ),
            )

        result_data = _read_json(result_path)
        if result_data is None:
            return SkeletonExportRunResult(
                log_tail=log_tail,
                exit_code=exit_code,
                error=(
                    "Unity exited without writing an export-result file. This usually means it "
                    "hit an error before the export could run -- see the log excerpt below."
                ),
            )

        outcomes = [
            SkeletonExportOutcome(
                model_path=m.get("model_path", ""),
                succeeded=bool(m.get("success")),
                error=m.get("error"),
                bone_names=m.get("bone_names"),
            )
            for m in result_data.get("models", [])
        ]
        return SkeletonExportRunResult(
            outcomes=outcomes,
            log_tail=log_tail,
            exit_code=exit_code,
            error=result_data.get("run_error"),
        )


def _read_json(path: Path) -> dict | None:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return None
    return data if isinstance(data, dict) else None


def _read_tail(path: Path, limit: int = LOG_TAIL_CHARS) -> str | None:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    return text[-limit:] if len(text) > limit else text
