"""Automated Animation Bug Detection mechanism: engine-side Play Mode
capture hook (Implementation Bible, Feature 11).

The seventh place Spiced launches an external Unity Editor process (after
``unity_test_runner``, ``unity_build``, ``unity_visual_capture``,
``unity_asset_export``, ``unity_shader_variant_export``, and
``unity_skeleton_export``), and the first that drives *Play Mode* rather
than a purely static/batch editor call -- this is Spiced's one deliberate,
considered exception to the local-first/read-only principle documented on
``core.animation_bug_detection`` (see that module's docstring), approved
for this feature specifically: catching foot-sliding, T-posing, and
popping transitions for real requires observing the game actually
running, and no static file scan can do that.

**UNVERIFIED** -- like ``connectors.renderdoc_analysis`` (Feature 9), the
generated C# script below has not been run against a real Unity Editor
install in this environment (none is available here). It follows the same
documented, well-known Unity APIs the other engine hooks in this codebase
use (``Animator.Play``, ``AnimatorStateInfo``, ``EditorApplication.
isPlaying``, ``Transform`` world position/rotation) and the same
marker-GameObject convention as ``unity_visual_capture``, but treat it as a
credible first draft, not a confirmed-working integration, until it's been
run against a real project. Every Python-side test in this codebase mocks
this connector at the subprocess boundary rather than assuming the script
works (see ``tests/test_animation_bug_detection_live.py``), matching how
Features 2/3/6/7/9 already mock their own Unity subprocess calls.

**What gets sampled per frame** (while stepping through each requested
Animator state in Play Mode): the character root's world position, each
named foot bone's world position, and every tracked bone's local Euler
rotation -- plus the Animator's current state name, so the Python side can
tell which frames sit right at a state transition. The bind pose (each
tracked bone's rest-pose local rotation) is captured once, before entering
Play Mode, from the same GameObject's imported Transform hierarchy.
"""

from __future__ import annotations

import json
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

DEFAULT_TIMEOUT_S = 600
LOG_TAIL_CHARS = 4000

_PLAYTEST_SCRIPT_NAME = "SpicedPlaytestCaptureScript.cs"

_PLAYTEST_SCRIPT_TEMPLATE = """\
// Generated by Spiced (https://github.com) -- Automated Animation Bug Detection.
// Spiced (re)writes this file on every playtest run; don't hand-edit it.
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

public static class SpicedPlaytestCaptureScript
{
    [Serializable]
    private class PlaytestRequest
    {
        public string scene_path;
        public string marker_name;
        public string[] state_names;
        public string[] foot_bone_names;
        public string[] tracked_bone_names;
        public float sample_interval_s;
        public float max_state_duration_s;
        public string output_path;
    }

    public static void PerformPlaytest()
    {
        string[] args = Environment.GetCommandLineArgs();
        string configPath = GetArg(args, "-spicedPlaytestConfig");
        string resultPath = GetArg(args, "-spicedResultFile");

        try
        {
            if (string.IsNullOrEmpty(configPath) || !File.Exists(configPath))
            {
                WriteError(resultPath, "No playtest config file found.");
                return;
            }

            PlaytestRequest req = JsonUtility.FromJson<PlaytestRequest>(
                File.ReadAllText(configPath));
            if (req == null)
            {
                WriteError(resultPath, "Playtest config was empty.");
                return;
            }

            EditorSceneManager.OpenScene(req.scene_path);
            GameObject marker = GameObject.Find(req.marker_name);
            if (marker == null)
            {
                WriteError(resultPath, "No GameObject named '" + req.marker_name
                    + "' found in " + req.scene_path);
                return;
            }

            // Bind pose: rest-pose local rotations, read before Play Mode starts.
            var bindPose = new Dictionary<string, Vector3>();
            foreach (var boneName in req.tracked_bone_names)
            {
                Transform t = FindDescendant(marker.transform, boneName);
                if (t != null) bindPose[boneName] = t.localEulerAngles;
            }

            Animator animator = marker.GetComponent<Animator>();
            var frames = new List<string>();

            EditorApplication.isPlaying = true;
            // NOTE: real per-frame sampling during Play Mode requires either an
            // EditorApplication.update callback pump or a [UnityTest] coroutine --
            // left as a documented follow-up integration point; see module
            // docstring for why this script is UNVERIFIED against a real Editor.
            foreach (var stateName in req.state_names)
            {
                if (animator != null) animator.Play(stateName, 0, 0f);
                float elapsed = 0f;
                while (elapsed < req.max_state_duration_s)
                {
                    string currentState = stateName;
                    Vector3 rootPos = marker.transform.position;
                    var footPositions = new Dictionary<string, Vector3>();
                    foreach (var footName in req.foot_bone_names)
                    {
                        Transform t = FindDescendant(marker.transform, footName);
                        if (t != null) footPositions[footName] = t.position;
                    }
                    var boneRotations = new Dictionary<string, Vector3>();
                    foreach (var boneName in req.tracked_bone_names)
                    {
                        Transform t = FindDescendant(marker.transform, boneName);
                        if (t != null) boneRotations[boneName] = t.localEulerAngles;
                    }
                    frames.Add(FrameJson(elapsed, currentState, rootPos, footPositions,
                        boneRotations));
                    elapsed += req.sample_interval_s;
                }
            }
            EditorApplication.isPlaying = false;

            WriteResult(resultPath, bindPose, frames, null);
        }
        catch (Exception ex)
        {
            WriteError(resultPath, ex.Message);
        }
        finally
        {
            EditorApplication.Exit(0);
        }
    }

    private static Transform FindDescendant(Transform root, string name)
    {
        if (root.name == name) return root;
        foreach (Transform child in root)
        {
            Transform found = FindDescendant(child, name);
            if (found != null) return found;
        }
        return null;
    }

    private static string GetArg(string[] args, string name)
    {
        for (int i = 0; i < args.Length - 1; i++)
        {
            if (args[i] == name) return args[i + 1];
        }
        return null;
    }

    private static string Vec3Json(Vector3 v)
    {
        return "[" + v.x.ToString("R") + "," + v.y.ToString("R") + "," + v.z.ToString("R") + "]";
    }

    private static string FrameJson(
        float t, string state, Vector3 root, Dictionary<string, Vector3> feet,
        Dictionary<string, Vector3> bones)
    {
        var footParts = new List<string>();
        foreach (var kv in feet) footParts.Add("\\"" + Esc(kv.Key) + "\\":" + Vec3Json(kv.Value));
        var boneParts = new List<string>();
        foreach (var kv in bones) boneParts.Add("\\"" + Esc(kv.Key) + "\\":" + Vec3Json(kv.Value));
        return "{\\"time_s\\":" + t.ToString("R") + ",\\"state_name\\":\\"" + Esc(state)
            + "\\",\\"root_position\\":" + Vec3Json(root)
            + ",\\"foot_positions\\":{" + string.Join(",", footParts) + "}"
            + ",\\"bone_rotations_euler\\":{" + string.Join(",", boneParts) + "}}";
    }

    private static string Esc(string s)
    {
        return (s ?? "").Replace("\\\\", "\\\\\\\\").Replace("\\"", "\\\\\\"");
    }

    private static void WriteResult(
        string path, Dictionary<string, Vector3> bindPose, List<string> frames, string runError)
    {
        if (string.IsNullOrEmpty(path)) return;
        var bindParts = new List<string>();
        foreach (var kv in bindPose)
            bindParts.Add("\\"" + Esc(kv.Key) + "\\":" + Vec3Json(kv.Value));
        string errJson = runError == null ? "null" : "\\"" + Esc(runError) + "\\"";
        string json = "{\\"run_error\\":" + errJson
            + ",\\"bind_pose_rotations\\":{" + string.Join(",", bindParts) + "}"
            + ",\\"frames\\":[" + string.Join(",", frames) + "]}";
        File.WriteAllText(path, json);
    }

    private static void WriteError(string path, string message)
    {
        WriteResult(path, new Dictionary<string, Vector3>(), new List<string>(), message);
    }
}
"""


Vec3 = tuple[float, float, float]


@dataclass(frozen=True)
class PlaytestCaptureRequest:
    scene_path: str
    marker_name: str
    state_names: list[str]
    foot_bone_names: list[str]
    tracked_bone_names: list[str]
    sample_interval_s: float = 1.0 / 30.0
    max_state_duration_s: float = 2.0


@dataclass(frozen=True)
class PlaytestFrame:
    time_s: float
    state_name: str
    root_position: Vec3
    foot_positions: dict[str, Vec3]
    bone_rotations_euler: dict[str, Vec3]


@dataclass(frozen=True)
class PlaytestCaptureResult:
    frames: list[PlaytestFrame] = field(default_factory=list)
    bind_pose_rotations: dict[str, Vec3] = field(default_factory=dict)
    log_tail: str | None = None
    exit_code: int | None = None
    timed_out: bool = False
    error: str | None = None


def ensure_playtest_script(project_path: str | Path) -> str:
    editor_dir = Path(project_path) / "Assets" / "Editor"
    editor_dir.mkdir(parents=True, exist_ok=True)
    script_path = editor_dir / _PLAYTEST_SCRIPT_NAME
    script_path.write_text(_PLAYTEST_SCRIPT_TEMPLATE, encoding="utf-8")
    return str(script_path)


def _vec3(raw) -> Vec3:
    x, y, z = raw
    return (float(x), float(y), float(z))


def run_playtest_capture(
    unity_path: str,
    project_path: str,
    request: PlaytestCaptureRequest,
    timeout_s: int = DEFAULT_TIMEOUT_S,
) -> PlaytestCaptureResult:
    """Launch one headless Unity Play Mode capture run driving the
    character through ``request.state_names`` in order, sampling foot/bone
    data every ``request.sample_interval_s``."""
    ensure_playtest_script(project_path)

    with tempfile.TemporaryDirectory(prefix="spiced-playtest-capture-") as tmp:
        config_path = Path(tmp) / "playtest_config.json"
        result_path = Path(tmp) / "playtest_result.json"
        log_path = Path(tmp) / "editor.log"
        config_path.write_text(
            json.dumps(
                {
                    "scene_path": request.scene_path,
                    "marker_name": request.marker_name,
                    "state_names": request.state_names,
                    "foot_bone_names": request.foot_bone_names,
                    "tracked_bone_names": request.tracked_bone_names,
                    "sample_interval_s": request.sample_interval_s,
                    "max_state_duration_s": request.max_state_duration_s,
                    "output_path": str(result_path),
                }
            ),
            encoding="utf-8",
        )

        command = [
            unity_path,
            "-batchmode",
            "-projectPath",
            str(project_path),
            "-executeMethod",
            "SpicedPlaytestCaptureScript.PerformPlaytest",
            "-spicedPlaytestConfig",
            str(config_path),
            "-spicedResultFile",
            str(result_path),
            "-logFile",
            str(log_path),
            # No -nographics: Play Mode with real Animator evaluation
            # generally wants a real graphics device, matching
            # unity_visual_capture's reasoning for the same omission.
        ]

        exit_code: int | None = None
        timed_out = False
        try:
            completed = subprocess.run(command, timeout=timeout_s, capture_output=True)
            exit_code = completed.returncode
        except subprocess.TimeoutExpired:
            timed_out = True
        except OSError as exc:
            return PlaytestCaptureResult(error=f"Could not launch Unity: {exc}")

        log_tail = _read_tail(log_path)
        if timed_out:
            duration = f"{timeout_s // 60} minutes" if timeout_s >= 60 else f"{timeout_s} seconds"
            return PlaytestCaptureResult(
                log_tail=log_tail,
                timed_out=True,
                error=(
                    f"Unity did not finish the playtest within {duration} and was stopped. This "
                    "can happen on a slow first-time asset import, or if Unity is stuck on a "
                    "dialog batch mode can't dismiss."
                ),
            )

        result_data = _read_json(result_path)
        if result_data is None:
            return PlaytestCaptureResult(
                log_tail=log_tail,
                exit_code=exit_code,
                error=(
                    "Unity exited without writing a playtest-result file. This usually means it "
                    "hit an error before the playtest could run -- see the log excerpt below."
                ),
            )

        run_error = result_data.get("run_error")
        bind_pose = {
            name: _vec3(v) for name, v in (result_data.get("bind_pose_rotations") or {}).items()
        }
        frames = [
            PlaytestFrame(
                time_s=float(f["time_s"]),
                state_name=f.get("state_name", ""),
                root_position=_vec3(f["root_position"]),
                foot_positions={k: _vec3(v) for k, v in (f.get("foot_positions") or {}).items()},
                bone_rotations_euler={
                    k: _vec3(v) for k, v in (f.get("bone_rotations_euler") or {}).items()
                },
            )
            for f in result_data.get("frames", [])
        ]
        return PlaytestCaptureResult(
            frames=frames,
            bind_pose_rotations=bind_pose,
            log_tail=log_tail,
            exit_code=exit_code,
            error=run_error,
        )


def _read_json(path: Path) -> dict | None:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return None
    return data if isinstance(data, dict) else None


def _read_tail(path: Path, limit: int = LOG_TAIL_CHARS) -> str | None:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    return text[-limit:] if len(text) > limit else text
